name: flutter_clean_template
description: Projek Untuk Clean Template Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.2
  ionicons: ^0.2.2

  # Networking
  retrofit: ^4.0.1
  dio: ^5.2.1+1

  # state_management
  flutter_bloc: ^8.1.3

  # other
  flutter_hooks: ^0.18.6
  get_it: ^7.6.0
  floor: ^1.4.2
  equatable: ^2.0.5
  oktoast: ^3.3.1
  awesome_dio_interceptor: ^1.0.0
  go_router: ^10.0.0
  # auto_route: ^7.2.0

  # CHANGE PACKAGE & ICON
  change_app_package_name: ^1.1.0
  icons_launcher: ^2.1.3

icons_launcher:
  image_path: 'assets/logo.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # auto_route_generator: ^7.2.0
  retrofit_generator: ^7.0.8
  floor_generator: ^1.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
